# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_field', models.CharField(max_length=255, null=True)),
                ('code_field', models.PositiveIntegerField(null=True)),
                ('date_field', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=250)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=250)),
                ('log_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.LogFormat')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Load'),
        ),
    ]
