# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180610_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='url_field_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
