# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_data_url_field_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='import_date_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
