# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_load_import_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='import_date_finish',
            field=models.DateTimeField(null=True),
        ),
    ]
