# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20180610_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='import_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
