# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180610_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='import_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
