# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Char'), (1, 'Int'), (2, 'DateTime')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Field')),
            ],
        ),
        migrations.CreateModel(
            name='LogFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_format', models.CharField(max_length=200)),
                ('regex', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='logfield',
            name='log_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logformat', to='log.LogFormat'),
        ),
    ]
