# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logformat',
            name='date_format',
            field=models.CharField(default='%d/%b/%Y:%H:%M:%S -0300', max_length=200),
        ),
        migrations.AlterField(
            model_name='logformat',
            name='regex',
            field=models.CharField(default='([(\\d\\.)]+) - - \\[(.*?)\\] "(.*?)" (\\d+) (\\d+) "(.*?)" "(.*?)"', max_length=250),
        ),
    ]
